const string_english = {
  app_name: "IResident",
  login: "Login",
  signup: "Registrate",
  email: "Email",
  password: "Password",
  welcome_to: "Welcome!",
  sign_in_to_continue: "Sign in to continue.",
  remember_password: "Remember password",
  get_into: "Get into",
  in_development: "In Development",
  i_forgot_password: "I forgot password",
  complete_following_register: "complete following register",
  name: "Name",
  first_name: "First name",
  last_name: "Last name",
  register: "Register",
  repeat_password: "Repeat password",
  you_are_not_part_of_iresident: "You are not part of iResident.",
  enter_the_code: "Enter the code of your complex",
  join_me: "Join me",
  surveillance: "Surveillance",
  regulation: "Regulation",
  guests: "Guests",
  mailbox: "Mail box",
  notification: "Notification",
  addressheader1: "Frontemare",
  addressheader2: "Residential",
  to_come: "To come",
  not_authorized: "Not authorized",
  defeated: "Defeated",
  in_place: "In place",
  delete: "Delete",
  share: "Share",
  myguest: "My guest",
  newguest: "New guest",
  ownvehical: "Own vehical",
  taxiorother: "Taxi or other",
  formofincome: "Form of income",
  registration: "Tuition",
  guestcompanies: "Number of companions of the \nguest",
  upto4company: "Up to 4 companions",
  morethan4company: "More than 4 companions",
  admissiondate: "Fecha de ingreso",
  daystostay: "Date of admission",
  myprofile: "My profile",
  changeuser: "Change user",
  guestaccess: "Guest access",
  allowentry: "Allow entry",
  denyentry: "Deny entry",
  scaninfo:
    "Scan the guest's code to verify their access status",
  checkcode: "Check code",
  dateofstay: "Date of stay",
  dashboardguide: "[Dashboard guardia]",
};


const string_spanish = {
  app_name: "iResident",
  login: "Inicio de sesion",
  signup: "Registrate",
  email: "Correo electrónico",
  password: "contraseña",
  welcome_to: "Bienvendid@! a",
  sign_in_to_continue: "Inicia sesión para continuar.",
  remember_password: "Recordar usuario.",
  get_into: "Ingresar",
  in_development: "In Development",
  i_forgot_password: "Olvide mi constraseña",
  complete_following_register: "Completa lo siguiente para \nregistrarte",
  name: "Nombre",
  first_name: "Primer nombre",
  last_name: "Apellido paterno",
  register: "Registrar",
  repeat_password: "Repetir contraseña",
  you_are_not_part_of_iresident: "Aún no eres parte de un grupo \niResident.",
  enter_the_code: "Ingresa el código de tu complejo",
  join_me: "Unirme",
  surveillance: "Vigilancias",
  regulation: "Reglamento",
  guests: "Invitados",
  mailbox: "Buzón",
  notification: "Notificaciones",
  addressheader1: "Frontemare",
  addressheader2: "Conjunto residencial",
  to_come: "Por llegar",
  not_authorized: " No autorizado",
  defeated: "Vencido",
  in_place: "En sitio",
  delete: "Eliminar",
  share: "Compartir",
  myguest: "Mis invitados",
  newguest: "Nuevo invitado",
  ownvehical: "Vehiculo propio",
  taxiorother: "Taxi u otro",
  formofincome: "Forma de ingreso",
  registration: "Matricula",
  guestcompanies: "Numero de acompañantes del \ninvitado",
  upto4company: "Hasta 4 \nacompañantes",
  morethan4company: "Más de 4 acompañantes",
  admissiondate: "Fecha de ingreso",
  daystostay: "Días de estancia",
  myprofile: "Mi perfil",
  changeuser: "Cambiar usuario",
  guestaccess: "Acceso a invitado",
  allowentry: "Permitir ingreso",
  denyentry: "Denegar ingreso",
  scaninfo:
    "Escanea el código del invitado para \nverificar el estado de su acceso",
  checkcode: "Verificar código",
  dateofstay: "Fecha de estancia",
  dashboardguide: "[Dashboard guardia]",
};

export default string_english;
